[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/criar-pix.php"
  to = "/.netlify/functions/criar-pix"
  status = 200
  force = true

[[redirects]]
  from = "/api/verificar-status.php"
  to = "/.netlify/functions/verificar-status"
  status = 200
  force = true
